### ISSUE TITLE
Unstable ingots repeatedly killing me

### ISSUE THREAD

**Issue by letschanator** [MJRLegends/Space-Astronomy-Feedback-#120]
Newest version
 
log- http://pastebin.com/iGXKz9bz 

I was trying to make a healing axe so I got an activated division sigle I made the unstable ingots than I noticed that they wern't turning red and orange like they were going to explode so I tryed the recipe (in a vinilla crafting table) and it didn't work I made sure it was the right recipe and it was so I than exited the crafting table and picked up the unstable ingots and than they just keep killing me. :(

**Comment by letschanator** [comment]
Never mind I went back in and turned keep inventory off and it just got rid of all my items but the unstable ingots still don't explode normally like there supost to

**Comment by MJRLegends** [comment]
Unstable ingots are ment to kill you if you dont craft what your making quick???

**Comment by MJRLegends** [comment]
Take a read of this http://ftbwiki.org/Unstable_Ingot

**Comment by thesixler** [comment]
I got the same issue as this guy, it's a real glitch. Normally the ingots will turn redder and explode, killing you if you wait too long. Instead of that happening, trying to craft the ingots into something like a healing axe doesn't work, the result of the recipes don't show up as if the recipe were wrong, AND the ingots don't get redder and explode. They stay white, forever. Then, when you close the crafting window, the ingots just fall out onto the ground, and stay there. But when you pick up the ingot or accidentally walk over it, it INSTANTLY kills you. And that makes your stuff go all over the place, or into a gravestone, but then when you open the gravestone, the ingot is still there, ready to kill you the second it enters your inventory. And it still won't craft into anything. So it's lethal and worthless.. When I cheat in the ingots they work just fine, but making them myself turns them into this buggy thing. I've used unstable ingots a lot so its weird to see them not working.

The only way I got rid of them was by using a ring of magnetism with a full inventory to drag the ingots over lava and burn them up. I died like 20 times before figuring it out.
