### ISSUE TITLE
NEI Crash 1.3.3

### ISSUE THREAD

**Issue by Darsam** [MJRLegends/Space-Astronomy-Feedback-#157]
3rd problem in the same modpack in the same version...

We will kill me if it was often said, but every time I look at a recipe with NEI... i crash.
I look with a other item, same thing.

**Comment by WalaoEgg0424** [comment]
@Darsam This is the Rotarycraft and PheumaticCraft Error i think , its been reported many times and theres record in Issue Tracker

4. https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/134 - Will be fixed - This is the crash with recipe in NEI!! THIS IS A MOD BUG!!!!!!! See link below https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/450

Although its fixed in v1.3.2 but MJRLegends updated all the mod to latest in v1.3.3 , I think i ma tell MJRLegends about this .

The only solution for not accidentely crash your world is doing these step.

1) In your world , go to your inventory.
2)Press "O" to disable the NEI
3)Dont ever press R to search for recipe , if you want the recipe , google it or ask me via skype 000> yimer1821 / RazorBlade0424

Hope that will help u :)

**Comment by Darsam** [comment]
Okay, thanks :)

**Comment by WalaoEgg0424** [comment]
@Darsam Your Welcome :)

**Comment by MJRLegends** [comment]
See https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/450
