### ISSUE TITLE
Apples and Trees

### ISSUE THREAD

**Issue by TheMrTomatoMan** [MJRLegends/Space-Astronomy-Feedback-#17]
on appletrees grow persimons i think that should not

**Comment by MJRLegends** [comment]
Sorry i dont understand what you mean

**Comment by piml38** [comment]
If you plant an apple tree sapling, it will grow a persimons. Have the same problem

**Comment by MJRLegends** [comment]
I will take a look at this in more detail soon and get back to you.

**Comment by WheresMyMtnDew** [comment]
I am also seeing this issue, when you plant an apple sapling- it grows into an oak tree. Sometimes the oak tree spawns with orchard fruits- sometimes persimmons, sometimes nothing at all. What is the point of having apple saplings that spawn oak trees- I mean oak tree saplings are a dime a dozen why waste an apple on a sapling that does not give you back any fruit? I wondered if this was intentional or if there was some bug or change to biomes o plenty that is not listed on their page. If this is intentional and or native to this modpack it would be good to know.

**Comment by MJRLegends** [comment]
This is not a major issue so will be fixed soon
