### ISSUE TITLE
Crash on world startup since update today

### ISSUE THREAD

**Issue by elliskid1022** [MJRLegends/Space-Astronomy-Feedback-#218]
I'd like to know if this is caused by the update or if something is wrong with the world. I'd hate to lose the world. Below is the crash log.
http://pastebin.com/FY4Ra2Xx (Changed to a pastebin link by MJRLegends)

It appears to do with a quarry in the aroma mining dimension. If there is a way to fix this I'd love to hear it. Thanks.

**Comment by MJRLegends** [comment]
It seems to be a problem with chunk loaders (codechicken.chunkloader), you could remove the Chicken chunks mod which will remove the chunk loaders from your world or use mcedit to remove them from your world. Also i have had this crash because and cant find the source or a fix apart from remove them and replace them when you get back in the world

**Comment by elliskid1022** [comment]
I ended up deleting the mining world to save my world and it worked okay.
DIdn't lose much. Thanks for the reply and also thanks for making a fun
modpack!

**Comment by MJRLegends** [comment]
Ok fairs
