### ISSUE TITLE
Crashing when trying to load sp world

### ISSUE THREAD

**Issue by trexus23** [MJRLegends/Space-Astronomy-Feedback-#221]
Hey can someone give me a hand not sure if a bug or a simple missclick( accidently clicked nei during fighting the ender dragon) and now i cannot connect to the game without crashing? http://pastebin.com/tf7stJ9X

**Comment by MJRLegends** [comment]
Guessing you fixed it then?

**Comment by trexus23** [comment]
Thought i had but now on trying to load  im getting the same error but in a different place now i cant even load the single player world

**Comment by MJRLegends** [comment]
It seems to be a problem with chunk loaders (codechicken.chunkloader), you could remove the Chicken chunks mod which will remove the chunk loaders from your world or use mcedit to remove them from your world. Also i have had this crash because and cant find the source or a fix apart from remove them and replace them when you get back in the world.

See #218
