### ISSUE TITLE
Enhaced Building Guide don't put blocks in the official server

### ISSUE THREAD

**Issue by Spellkaze** [MJRLegends/Space-Astronomy-Feedback-#250]
As the title says, the Enhaced Building Guide don't put blocks in the official server (have not tested in other servers tho)
This works in singleplayer, but in the server, with protected or not protected zones it don't put any blocks. the blocks are not consumed or produce any particle effect. The ghost blocks guide works fine.
2 pictures, one in singleplayer, and the other one in the server
![2016-03-20_12 45 00](https://cloud.githubusercontent.com/assets/10790732/13905971/d41d14f6-ee9b-11e5-8c8e-2fd22e2b95c5.png)
![2016-03-20_13 08 13](https://cloud.githubusercontent.com/assets/10790732/13906110/d756d87c-ee9c-11e5-84a7-a0cabdf2909c.png)
(the issue is the same in the overworld, just did not want to reveal the coordinates)

**Comment by MJRLegends** [comment]
I think you just need to allow the block to build in the claim, but im not sure that the fake player will be, i will look in to it

**Comment by Spellkaze** [comment]
it don't work on unprotected zones either, is not disabled in the server configs?

**Comment by MJRLegends** [comment]
The server config are the same as the client ones(single player) I will have a look in to it

**Comment by MJRLegends** [comment]
@Spellkaze the solution is in for this https://github.com/KaiKikuchi/GriefPreventionPlus/issues/89

**Comment by Spellkaze** [comment]
No, it does not seem to work, i mean, even with autotrust or , or even in not claimed zones the enhaced don't take the blocks and build or with the fake player #OpenModsFakePlayer trusted

**Comment by MJRLegends** [comment]
How weird

**Comment by Unistic** [comment]
The Open Block Enhanced Building Guide has never worked on any server that I've ran or played on. It seems to only work on single player. The reason that I gather is because before placing a block it checks to see if the player is set to OP. In single player you are OP that's why it works. On a server you wouldn't be so it doesn't work. That's my opinion. Some people just think there's a server plugin that interferes with it but i don't think that's the case.

The only builder that works to auto build shapes/sizes on a server is the one within RF Tools. Wish that the author of EBG will look at how that builder works and incorporate that into a fix.
