### ISSUE TITLE
No Mouse Pointer

### ISSUE THREAD

**Issue by Nyxxaa** [MJRLegends/Space-Astronomy-Feedback-#280]
Been playing for a while when I noticed that in the ESC menu and on the title screen I have no mouse pointer. I can still select stuff if the mouse highlights it but I  never see the mouse in these screens. Secondly I cannot sprint, I am uncertain as to why this might be.

**Comment by johnrobertwilson** [comment]
I'm also experiencing no mouse pointer! using OSX 10.11.4 and FTB launcher

**Comment by johnrobertwilson** [comment]
Ah, turns out I should've read further and taken the mod author's advice to search closed issues.

https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/65

https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/70

https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/171

This seems to be a bug with another mod.
