### ISSUE TITLE
Won't craft DNA analyzer

### ISSUE THREAD

**Issue by Cooth** [MJRLegends/Space-Astronomy-Feedback-#481]
Playing your pack for the first time and got to the Advanced Genetics quest line which wants me to craft the DNA analyzer but when I put the 8 Iron into the crafting grid it doesn't come up with anything? Also the game is lagging alot, as in when I'm breaking lots of blocks or bettling mobs the game replaces some blocks or doesn't register hits. Checking the Task manager the CPU and memory is over 60% and all my other mod packs run fine. The setting I always play the same which are fast graphics, decreased particles, no clouds, 8 chunk render distance and minimum smooth lighting? I think this modpack has great potential and am really looking forward to playing it.

**Comment by MJRLegends** [comment]
You need to put 8 iron and then a magnifier in the in center, it does show this in the nei but the magnifier doesn't show up very well and blends in to the background tbh. 

And about the game lagging thats due to the mod pack is a very big, maybe as much as i dont support optifine and i hate it but maybe give it a try
