### ISSUE TITLE
Lots of lag even with a lot of allocated RAM

### ISSUE THREAD

**Issue by PlagueOfCute** [MJRLegends/Space-Astronomy-Feedback-#602]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue] yes

### Steps to Reproduce Issue
1. Play the modpack

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.5.5 but also happened in previous versions

### Additional Information
I don't exactly know why but this modpack gets super laggy for me, the most RAM I've allocated into it was 10 GB and least was 2 GB and it seems to lag just as much in both cases and I don't know why, are there certain settings that should be turned on/off when playing this modpack to help with this?

**Comment by MJRLegends** [comment]
Not enough information to look at this issue....

**Comment by AsderKnaster** [comment]
I have a similar problem.
Further information: allocating 6.5 GB of RAM to the game (the most i can afford) makes it playable for 30 min or so then the game freezes in intervalls becoming shorter. Looking up the RAM usage of my PC you see that it is full for the duration of the freeze (20-60 seconds) CPU ist not at 100% neither is the GPU. Playing for longer (and not doing much in the game) freezes become more frequent and longer

**Comment by MJRLegends** [comment]
There is nothing i can do without advanced details as i dont get the same issue

**Comment by AsderKnaster** [comment]
Maybe you can mention which kind of details you want to know?

**Comment by xX-Gigi-Xx** [comment]
AsderKnaster I also had the same problem until yesterday ... I had lag issues although I have 12 GB of Ram allocated, maximum 50% CPU used and a connection with only 40 of maximum ping ... I solved the problem by updating java through Microsoft internet Explorer and no Microsoft Edge because the latter does not support java extensions. I had the version 8 update 66, while it was already 8 update version 111 exit and that made me lag 1000-1500 levels for leading me to continuously ping ... I just upgraded, I restarted the modpack and you're extremely fluid back ... try updating java, can be the problem.
