### ISSUE TITLE
JustAFewFish possibly causing crashing issue

### ISSUE THREAD

**Issue by badgernz** [MJRLegends/Space-Astronomy-Feedback-#904]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
JustAFewFish seems to be crashing 2 out of our 4 servers upon loading the world after the update and after disabling chunkloading for an unrelated mod, upon reversing said chunkloading change, the issue still arose. We removed JustAFewFish from the 2 problematic servers to bypass the issue at this time.

### Steps to Reproduce Issue
I have been unable to reproduce this issue on our other 2 servers

**Crash log/Log (if applicable):** https://pastebin.com/EAND5bZv

**Version of Mod Pack using:** 1.6.8

**Comment by theindiandood** [comment]
I posted my fix [here](https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/899#issuecomment-315494174) to fix your server world. I believe this happens because of a bug in the mod that spawns Cod and Salmon fish entities in excess near a fake player entity or chunk loading (not 100% about chunk loading) when the player is in another world. Your server probably gave out after too many entities spawned.

Let me know if the fix works!
